baseURL = "https://example.com/"
languageCode = "en-gb"
title = "Homepage"

theme = "papaya"

[taxonomies]
  tag = "tags"

# The value of pre is the icon name in https://feathericons.com/
[menu]
  [[menu.main]]
    name = "Services"
    pre = "services"
    url = "/services/"
    weight = 1
  [[menu.main]]
    name = "Industries"
    pre = "industries"
    url = "/industries/"
    weight = 2
  [[menu.main]]
    name = "Partners"
    pre = "partners"
    url = "/partners/"
    weight = 3
  [[menu.main]]
    name = "Contact us"
    pre = "partners"
    url = "/contact-us/"
    weight = 4

[params]
  dateFormat = "Jan 2, 2006"
  authorName = "made by Roma"
  googleAdSense = "ca-pub-0000000000000000"
  googleAnalytics = "UA-000000000-1"

[social]
  twitter = "Emaxple"